"""`our_life` · core：纯函数层。

本包**不导入任何 `plugin.sdk.*`**——数值模型、行为聚合、注入文案、配置视图与错误码
全是可独立单测的纯逻辑。有状态、需要宿主通道的部分都在 `services/`。
"""

from __future__ import annotations

from .behavior import (
    ASSISTANT_TURN_TYPES,
    USER_TURN_TYPES,
    BehaviorSummary,
    TurnRecord,
    empty_summary,
    gap_hours,
    local_day,
    local_hour,
    normalize_turn,
    select_new_turns,
    summarize_turns,
)
from .codes import PANEL_ERROR_CODES, camel_case, is_panel_code
from .configuration import (
    MAX_TICK_SECONDS,
    MIN_TICK_SECONDS,
    DecaySettings,
    GrowthSettings,
    InjectSettings,
    NeglectSettings,
    OurLifeSettings,
)
from .injection import (
    TRIGGER_COMPANY,
    TRIGGER_CRISIS,
    TRIGGER_DAILY_GREET,
    TRIGGER_INTERVAL,
    TRIGGER_TIER_CHANGE,
    build_text,
    resolve_ai_behavior,
)
from .model import (
    AFFECTION_TIERS,
    HEALTH_TIERS,
    MAX_VALUE,
    MIN_VALUE,
    MOOD_TIERS,
    STAT_NAMES,
    TIER_BOUNDS,
    TIER_CROSSING_MARGIN,
    Stats,
    advance_streak,
    apply_day_greet,
    apply_decay,
    apply_neglect,
    apply_streak_bonus,
    apply_turn_gain,
    clamp_value,
    crosses_tier_boundary,
    eventful_tier_transitions,
    is_crisis,
    neglect_entitlement_days,
    streak_milestone_bonus,
    tier_index_of,
    tier_of,
    tier_transitions,
)

__all__ = [
    "AFFECTION_TIERS",
    "ASSISTANT_TURN_TYPES",
    "BehaviorSummary",
    "DecaySettings",
    "GrowthSettings",
    "HEALTH_TIERS",
    "InjectSettings",
    "MAX_TICK_SECONDS",
    "MAX_VALUE",
    "MIN_TICK_SECONDS",
    "MIN_VALUE",
    "MOOD_TIERS",
    "NeglectSettings",
    "OurLifeSettings",
    "PANEL_ERROR_CODES",
    "STAT_NAMES",
    "TIER_BOUNDS",
    "TIER_CROSSING_MARGIN",
    "TRIGGER_COMPANY",
    "TRIGGER_CRISIS",
    "TRIGGER_DAILY_GREET",
    "TRIGGER_INTERVAL",
    "TRIGGER_TIER_CHANGE",
    "Stats",
    "TurnRecord",
    "USER_TURN_TYPES",
    "advance_streak",
    "apply_day_greet",
    "apply_decay",
    "apply_neglect",
    "apply_streak_bonus",
    "apply_turn_gain",
    "build_text",
    "camel_case",
    "clamp_value",
    "crosses_tier_boundary",
    "empty_summary",
    "eventful_tier_transitions",
    "gap_hours",
    "is_crisis",
    "is_panel_code",
    "local_day",
    "local_hour",
    "neglect_entitlement_days",
    "normalize_turn",
    "resolve_ai_behavior",
    "select_new_turns",
    "streak_milestone_bonus",
    "summarize_turns",
    "tier_index_of",
    "tier_of",
    "tier_transitions",
]
